### ISSUE TITLE
No dotenv on load

### ISSUE THREAD

**Issue by Mikkel-Coder** [Sh1tters/P2-Remote-inspection-and-exploration-using-camera-drone#14]
If no `.env` file has been created, the key is an empty string. This should raise an error!

https://github.com/Frier03/P2-Remote-inspection-and-exploration-using-camera-drone/blob/64ed89c9b72cb13b1f1ef976ab16f20ef7a1a4ed/backend/helper_functions.py#L33

**Comment by Frier03** [comment]
Issue fixed in pull request: https://github.com/Frier03/P2-Remote-inspection-and-exploration-using-camera-drone/commit/89f9f278ac36e534bb90bdbceab54c3ff210d101

**Comment by Mikkel-Coder** [comment]
Looks alright!
